name: greggs
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  api:
    path: ./packages/api
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http: ^1.1.2
  intl: ^0.18.0
  products_repository:
    path: ./packages/products_repository

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - env/
    - assets/images/
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/barlow/Thin.ttf
          weight: 100
        - asset: assets/fonts/barlow/ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/barlow/ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/barlow/ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/barlow/Light.ttf
          weight: 300
        - asset: assets/fonts/barlow/LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/barlow/Regular.ttf
          weight: 400
        - asset: assets/fonts/barlow/Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/barlow/Medium.ttf
          weight: 500
        - asset: assets/fonts/barlow/MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/barlow/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/barlow/SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/barlow/Bold.ttf
          weight: 700
        - asset: assets/fonts/barlow/BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/barlow/ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/barlow/ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/barlow/Black.ttf
          weight: 900
        - asset: assets/fonts/barlow/BlackItalic.ttf
          weight: 900
          style: italic
