name: api
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  chopper: ^7.0.9
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.7
  chopper_generator: ^7.0.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
